# -*- coding: utf-8 -*-
"""code_test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lY6j7gPdAdI6ZWkyCUDRQHmkkmfzyCa5

**REVERSE string**
"""

txt = "Hello World"[::-1]
print(txt)

"""**IS PRIME**"""

def prime(num):
  
  for i in range(2,num):
    
    if (num % i == 0):
      print(num,' is not prime')
      break
  else:
      print(num,' is a prime')

prime(43)

b=0
for a in range(800):
  if b == 101:
    break
    # print(a,'--')
  if a > 1:
    for i in range(2,a):
      
      if (a % i == 0):
        # print(a,' is not prime')
        break
    else:
      if b == 100:
        print(a,' is a prime',b)  
      b=b+1

"""**question example**"""

def func(a,b = 30, c = 70):
  print(a,b,c)
  print(a)
  print(b)
  print(c)

func(100,"welcome")